name: 'build android'
on:
  workflow_call

jobs:
  build-android:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2
      - name: Install
        run: npm install
        working-directory: ./

      - name: Setting up developer environment
        run: npx gulp setupDev
        working-directory: ./Package
        
      - name: Gulp (Android)
        run: npx gulp buildAndroid
        working-directory: ./Package
  