name: 'build android'
on:
  workflow_call

jobs:
  build-android:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2
      - name: Setting up developer environment
        run: |
          npm install
          npx gulp setupDev
        working-directory: ./Package

      - name: Install packages for Playground
        run: |
          npm install
        working-directory: ./Apps/Playground

      - name: Gulp (Android)
        run: npx gulp buildAndroid
        working-directory: ./Package
  