name: 'build ios'

on:
  workflow_call

jobs:
  build-iOS:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2

      - name: Install
        run: npm install
        working-directory: ./

      - name: Setting up developer environment
        run: npx gulp setupDev
        working-directory: ./Package

      - name: Clean and Install Pods
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install
        working-directory: ./Apps/Playground

      - name: Gulp (iOS)
        run: npx gulp buildIOS
        working-directory: ./Package
