name: Test BabylonNative Protocol compatibility
on:
  workflow_dispatch:
    inputs:
      NPM_Mask:
        description: 'NPM versions mask'
        required: true 
        type: string
        default: 5.*.*

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: NPM Install
      run: npm install
      working-directory: ./Apps/TestProtocol
    - name: Run tests
      run: npm run testPackages ${{ github.event.inputs.NPM_Mask }}
      working-directory: ./Apps/TestProtocol
    - name: Upload Result 
      uses: actions/upload-artifact@v2
      with:
          name: NPMCompatibility
          path: |
            ./compatibility.json