name: 'build test android'

on:
  workflow_call

jobs:
  build-test-android:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: BabylonReactNative
          path: ./artifact

      - name: Install build package
        run: |
          npm install ../../artifact/babylonjs-react-native-0.0.1.tgz
          npm install
        working-directory: ./Apps/Playground

      - name: Gulp (Android)
        run: |
          npm install
          npx gulp buildAndroid
        working-directory: ./Package
  